matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js: '12'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
  - os: windows
    language: node_js
    node_js: '12'
    env:
    - YARN_GPG=no
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "windows" ]; then
    export NODEPATH=$(where.exe node.exe)
    export PROJECTDIR=$(pwd)
    export YARNCACHE=$(yarn cache dir)
    export TEMPDIR=$LOCALAPPDATA\\Temp

    powershell Add-MpPreference -ExclusionProcess ${NODEPATH}
    powershell Add-MpPreference -ExclusionPath ${YARNCACHE}
    powershell Add-MpPreference -ExclusionPath ${PROJECTDIR}
    powershell Add-MpPreference -ExclusionPath ${TEMPDIR}

    echo "DisableArchiveScanning..."
    powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableArchiveScanning \$true'"

    echo "DisableBehaviorMonitoring..."
    powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableBehaviorMonitoring \$true'"

    echo "DisableRealtimeMonitoring..."
    powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableRealtimeMonitoring \$true'"
  fi
  yarn install --network-timeout 1000000
script:
- |
  if [ "$TRAVIS_OS_NAME" == "windows" ]; then
    yarn dist-win
  else
    yarn dist-mac
  fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: releases
  draft: true
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: JLBAyE1qr4V0Vj3GiGqav2a8D46OnVQza3sQwdGXt1zKknFeL+vCE6Ww9wZc4zizdgk+iqDKJ4c/KgFNI/rn+gThDkEb3KTrXST9A9h2F3AoIk3UWwX3U6S880yWel+cOEFShVDIc2aZBduA7fhvhCjVRXmqF3+UHYe3xW4ivEcVrFBAW3FAoC7j+mKAqXgP3cH6XDa8dJhK/Tu15j+OoRFvNR9bCtm/qonLwWjrRpz2tKSYegUwrohWQJ80ck1CsPTeF5G/KR5aLqvzl9Xodl9lkbLBZSMv004LBpsae21UtMn3wLOi+16TO/XELOgDMj2ddH7OSZj2mv/ialuRtRZ8DBYu/x3Jo4lp7bJHTdQxNc0H8gjRouxmvPAkpjvlD6Dk0z3XNELm4/OVZk8SevKm+MMDKHmNuaFeTijewgO1KhIyM76EA78IutWEPBLLLGTlO+rlCuZH8B3d+yntn/DTYexOJ6/DM9HJwCDinC1l1AA4hz77XlWOGisY7T7oYEouXrteeqdey9QbWi1doe5aJugfexvxZ4CctmsIlbgZVzBEZPKAAaV+Qd6KAmyddc/3SX4t/VUl3Mycde5BvgThFgb5BUbZYnpRjlF6GXnnwTzH75fWmPNGC8y1epEH/TGm+ju/mVD0BBNXv3c+2tEfd3qCpuZJbJqQLEOOuGA=
  file: 
    - release-builds/RocksmithManagerInstaller.dmg
    - release-builds/RocksmithManager-macos-x64.zip
    - release-builds/RocksmithManager-win32-x64.zip
    - release-builds/RocksmithManagerInstaller.exe
  on:
    repo: sandiz/rs-manager
