name: Github CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build-mac:
    name: "MacOS build"
    env:
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    runs-on: macOS-10.14    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run build script (mac)
      run: |
        yarn install
        yarn dist-mac
    - uses: sandiz/upload-release-action@releases/v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: 'release-builds/Rocksmith*'
        file_glob: true
        tag: 'github-ci-build'
        overwrite: true
        draft: true
  build-win:
    name: "Windows build"
    env:
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run build script (windows)
        run: |
          npm install --vs2015 -g windows-build-tools & yarn install & yarn dist-win
      - uses: sandiz/upload-release-action@releases/v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'release-builds/Rocksmith*'
          file_glob: true
          tag: 'github-ci-build'
          overwrite: true
          draft: true
